server:
  listen: 8080
  workers: 3

  upstreams:
    - id: upstream1
      url: https://jsonplaceholder.typicode.com

    - id: dummy
      url: https://dummyjson.com

    - id: myProfile
      url: https://github.com/Deep-Saha1925
  headers:
    - key: x-forward-for
      value: '$ip'

    - key: Authorization
      value: "Bearer xyz"

  rules:
    - path: /test
      upstreams:
        - dummy

    - path: /my
      upstreams:
        - myProfile

    - path: /
      upstreams:
        - upstream1